- name: Update Servers
  hosts: testservers
  become: yes
  become_method: sudo
  tasks:
  - name: "Update Repository cache"
  apt:
  update_cache: true
  cache_valid_time: 3600
  force_apt_get: true
  - name: Update all packages to their latest version
     ansible.builtin.apt:
       name: "*"
       state: latest
