---
- name: Chrony time update
  hosts: testservers
  become: true
  become_user: root
  connection: ssh
  tasks:
    - name: Update Redhat
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Rocky' or ansible_distribution == 'Fedora'
    - name: Package installation
      ansible.builtin.dnf:
        name:
          - chrony
        state: latest
        update_cache: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Rocky' or ansible_distribution == 'Fedora'
    - name: Deploy chrony.conf template
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/waltdundore/control-repo/production/templates/etc/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: 644
        backup: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Rocky' or ansible_distribution == 'Fedora'
    - name: Restart chronyd
      ansible.builtin.service:
        name: chronyd
        state: restarted
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'  or ansible_distribution == 'Rocky' or ansible_distribution == 'Fedora'
