---
- name: Monolithic update
  hosts: testservers
  become: true
  become_user: root
  connection: ssh
  tasks:
    - name: Update Redhat
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
    - name: Package installation
      ansible.builtin.dnf:
        name:
          - chrony
        state: latest
        update_cache: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
    - name: Deploy chrony.conf template
      ansible.builtin.get_url:
        url: /var/lib/awx/projects/_11__ansible_control_repository/templates/etc/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: 644
        backup: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
    - name: Restart chronyd
      ansible.builtin.service:
        name: chronyd
        state: restarted
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat
        Enterprise Linux' or ansible_distribution == 'RedHat'
