---
- name: Monolithic update
  hosts: testservers
  become: true
  user: wdundore
  connection: ssh
  tasks:
    - name: Install apache
      ansible.builtin.apt:
        name:
          "*"
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Install httpd
      ansible.builtin.yum:
        name:
          "*"
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
