---
- name: Chrony time update
  hosts: testservers
  become: true
  become_user: root
  connection: ssh
  tasks:
    - name: Update Redhat
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
    - name: Package installation
      ansible.builtin.dnf:
        name:
          - iperf3
        state: latest
        update_cache: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
    - name: Package installation
      ansible.builtin.dnf:
        name:
          - nmap
        state: latest
        update_cache: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
    - name: Package installation
      ansible.builtin.dnf:
        name:
          - iperf3
        state: latest
        update_cache: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
    - name: Package installation
      ansible.builtin.dnf:
        name:
          - wireshark
        state: latest
        update_cache: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
