---
name: Ansible Lint
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps: 
    -uses: actions/checkout@v2
    -name: Lint ansible playbook
    uses: waltdundore/control-repo@production
    with: main.yaml
